const contractAddress = "0x46Dd4b3d53E1cEE94eD6597C6E82aFFe65AAF8dC"; // Replace with your own contract address
const chain = 'polygon'; // goerli, polygon, or ethereum

const welcome_h1 = "LONELY PANDAS STORE";
const welcome_h2 = " ";
const welcome_p = 'If it keeps saying waiting for transaction then please check your wallet or your opensea account, nfts may already be minted';
const h1_presale_coming_soon = "Phase 1 Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "  Phase  1  is  live  "  ;
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Phase 1 Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = " ";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. Please try again.";
